### ISSUE TITLE
Creating an Engineering Model Setup from a Source Model returns error code

### ISSUE THREAD

**Issue by jaapatstariongroup** [STARIONGROUP/COMET-WebServices-Community-Edition#373]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I tried to create a new Engineering Model Setup using an exiting model on the server as a Source Model.
This returned the following error code:
![image](https://github.com/user-attachments/assets/ced1a9f6-a6f0-43e6-b4e0-d31165a37ed2)

Trying to do the same with an earlier version of that Source Model works without any issues.

**Solution:**
Seems like, in this case, an ArrayParameterType's ParameterTypeComponents are not in the originalToCopyMap in ModelCreatorManager.CreateEngineeringModelSetupFromSource, line 155

**Comment by lxatstariongroup** [comment]
@samatstariongroup 
Problem here is that ArrayParameterType is en subclass of ComponentParameterType.
In GetDeep of the ComponentParameterTypeService a GetShallow is performed to get all CompoundParameterTypes, including the ArrayParameterTypes.
To get the ParameterTypeComponent data for this, the result list of ComponentParameterTypes of the mentioned GetShallow gets filtered and casted to a List of ComponentParameterTypes using a GetType() == typeof(ComponentParameterType). GetType)_ returns the actual type, which is in case of an ArrayParameterType of course NOT "exactly" a ComponentParameterType.
Therefore, ComponentParameterTypes are not found here and the ArrayParameterType's Components cannot be found and added to the result of the initial ComponentParameterTypeService.GetDeep execution. 
Of course they can also not be found by the ResolveCopy method of the ArrayParameterType DTO, because elements were missing in the result of ComponentParameterTypeService.GetDeep.
This leads to the error of unfound copy in ModelCreatorManager.CreateEngineeringModelSetupFromSource.

Using result.OfType<ComponentParameterType>instead of the GetType() == typeof(ComponentParameterType) in ComponentParameterTypeService solves the problem.
CodeGen needed to be changed. This was tested and it works. IntegrationTesting will follow...
